### ISSUE TITLE
Console error in extracting data

### ISSUE THREAD

**Issue by Kyraze** [Decathlon/ara#120]
Here I am again, ahah.

![image](https://user-images.githubusercontent.com/44932677/59276443-98ce9280-8c5e-11e9-893d-eddcbf4b3c5b.png)
![image](https://user-images.githubusercontent.com/44932677/59276545-cca9b800-8c5e-11e9-86aa-23be54027cd6.png)

So I did get a 200 OK answer to my call which is supposed to upload the report. But in the console that launches the server here are the logs : 
[console log.txt](https://github.com/Decathlon/ara/files/3276822/console.log.txt)

**Comment by Kyraze** [comment]
Also when I go to "EXECUTIONS & ERRORS" 
Server side has error : 
server_1  | 2019-06-11 14:26:15.977  WARN 1 --- [nio-8080-exec-6] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed tovalidate connection com.mysql.jdbc.JDBC4Connection@11acc85c (No operations allowed after connection closed.)

**Comment by dktsni** [comment]
Hi @Kyraze !

I just checked your zip file, and it seems that the `cycleDefinition.json` as a typo in it. You have `PlatformRules` instead of `platforms_rules` just after the `blockingValidation` part. 

This cause the ARA parser to not find the block, and leads to a NullPointerException.

Could you try by replacing `PlatformRules` in `platforms_rules` ?

**Comment by Kyraze** [comment]
Hi @dktsni ,

Yes that was it! I tried it earlier in the week and the server did treat the .zip, but it didn't export the postman reports in it, but it did create a scenario with 0 test and 0 step.

**Comment by dktsni** [comment]
Hi @Kyraze,

Yes it didn't export the postman reports due to te lack of `platform_rules`, and this happen after the creation of the scenario 

So, does this issue fixed ?

**Comment by dktsni** [comment]
Hi @Kyraze,

I guess that this issue is fixed. If you want, we've just release the version 4.0.0 of ARA which provides a complete documentation about how to upload reports in it (available [here](https://github.com/Decathlon/ara/blob/master/doc/uploads/UploadPostman.adoc) )

I close the issue, feel free to reopen it if you have any further question :)
