### ISSUE TITLE
Data persistence

### ISSUE THREAD

**Issue by Kyraze** [Decathlon/ara#122]
Hello,

From last time and today I kind of forgot how to launch ARA.
`docker run -d -p 5000:5000 --name registry registry:2
docker login`

From here, I was wrong so could you correct me :
in the ara_root/db
`./manage-dh.sh start /c/jdd/ara_db`
But there wasn't any container so I did : 
`./manage-dh.sh create/c/jdd/ara_db` 
I am pretty sure that I used the same path last time since I created for it, but I'm not sure.
But when I went to ARA_ROOT/docker : 
`make run-version COMMIT_REF=3.1.1 DOCKER_REGISTRY=registry`

I was told that ara_db_1 couldn't be started, because the port was already in use, so I went back and stopped the previous ara_db container and relaunched the instruction and it did start the server but then the data was lost

**Comment by dktsni** [comment]
Hi @Kyraze,

I guess you use Windows ? We have an issue on version 3.X.X which in some Windows version, the mout from your Windows to the Docker image can't be achieved (the bug is from Docker for Windows...). 

Also you don't have to do the `./manage-db.sh create /c/jdd/ara_db` everytime you start your ARA instance. Do it once when you install ARA locally, and then just use `./manage-db.sh stop` to stop your ara instance and `./manage-db.sh start` to start it (`start` and `stop` doesn't take any arguments).

In version 4.0.0 we decide to remove the data persistency for local installations, since local install is only designed to test the software and not actually run a dedicated ARA instance.
So I can suggest two things : 
-> Upgrade to version 4.0.0 and do local testing on your Windows, but don't shutdown the server until the end of your test or you'll loose all your datas.
-> Install ARA on a dedicated instance (usually a GNU/Linux server) with a proper MySQL database connected to it to persist your datas.
