### ISSUE TITLE
Add the reporting section of pom.xml

### ISSUE THREAD

**Issue by qualitesys** [Decathlon/ara#228]
I would like to produce the maven site static html docs for the project

It is possible to add the reporting section in pom.xml files (compulsory since maven 3), like for example :
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>2.9</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.7.1</version>
            </plugin>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>5.2.4</version>
            </plugin>
        </plugins>
    </reporting>

To make sure it works, simply run "mvn site" command

Thanks for your help

**Comment by omar-chahbouni-decathlon** [comment]
Hi, thank you for your feedback and your interest for ARA!
This is a good idea, but this cannot be shipped with the current version (4.1.0) because it is currently being finalized.
However, this will be taken into account for the next version, for which the development will begin next week. You can keep track of the updates from time to time.

The ARA team
