### ISSUE TITLE
Remove the '#' in the ARA front end URLs

### ISSUE THREAD

**Issue by dktsni** [Decathlon/ara#23]
Remove the useless '#' in the ARA front end URLs like in `https://localhost:8080/#/management/projects`

**Comment by omar-chahbouni-decathlon** [comment]
Issue was re-opened because it was causing problem in the navigation (showing a **Whitelabel Error Page** when entering an url that is not a base url...)  when it was deployed on the server. It may be taken into account when ARA will be 'dockerised' , as it gets easier to configure the front container alone (unlike a jar containing both the back-office and the front office...)
