### ISSUE TITLE
Add "JIRA" bugtracker adapter

### ISSUE THREAD

**Issue by JulienBarlet** [Decathlon/ara#4]
As the native "Rational Team Concert" adapter which allow to make relations between "problems" in ARA and "Defect" in the bugtracker, it will be wonderful to make the same relation with JIRA.

**Comment by dktsni** [comment]
Here is some technical details to help : 

There is a DefectAdapter interface to implement for JIRA.
It is currently implemented for RTC (`RtcDefectAdapter`) and GitHub (`GithubDefectAdapter`)
The person doing this issue should create a class (like `JiraDefectAdapter`) implementing it.


The adapter is called several times:
* Update all problem statuses based on their defect statuses at application startup
* Then, every minute, asks JIRA for updated defects since last indexing ⇒ update the problems with such modified defects
* We use the defect status to open or close the defect
* If closed, we store the last closing date on the problem

Also, there will be new JIRA-specific settings to add in SettingProviderService.getDefectDefinitions()

If JIRA does not support querying defects modified since a date, perhaps add a supportsIncremental() method to the DefectAdapter interface and then make ARA do full-indexing every so and then
